spring:
  data:
    mongodb:
      uri: mongodb://sample:sample@mongodb:27017/customer?authSource=admin&readPreference=primary&ssl=false
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092