version: "3.9"

networks:
  sample:
    driver: bridge

volumes:
  kafka-zookeeper-data:
    driver: local
  kafka-data:
  mongodb-data:

services:

  mongodb:
    container_name: mongodb
    image: mongo:5.0.3
    restart: always
    ports:
      - published: 27017
        target: 27017
        mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: sample
      MONGO_INITDB_ROOT_PASSWORD: sample
      MONGO_INITDB_DATABASE: sample
    volumes:
      - mongodb-data:/data/db
    networks:
      - sample

  kafka-zookeeper:
    container_name: kafka-zookeeper
    image: bitnami/zookeeper:latest
    restart: always
    ports:
      - published: 2181
        target: 2181
        mode: host
    volumes:
      - kafka-zookeeper-data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - sample

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    restart: always
    ports:
      - published: 9092
        target: 9092
        mode: host
      - published: 9093
        target: 9093
        mode: host
    volumes:
      - kafka-data:/bitnami
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
    depends_on:
      - kafka-zookeeper
    networks:
      - sample

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui
    restart: always
    ports:
      - published: 9898
        target: 8080
        mode: host
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - sample